import { useState, useEffect } from 'react';
import { Brain, AlertTriangle, TrendingUp, Zap } from 'lucide-react';
import { aiInsights } from '../services/api';
import { SectionCard, StatusBadge, LoadingState, EmptyState } from '../components/ui/UIComponents';
import { formatDateTime } from '../utils/helpers';

const RISK_COLORS: Record<string, string> = {
  LOW: '#15803d',
  MEDIUM: '#b45309',
  HIGH: '#c2410c',
  CRITICAL: '#b91c1c',
};

export default function AIInsightsPage() {
  const [predictions, setPredictions] = useState<any[]>([]);
  const [anomalies, setAnomalies] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      aiInsights.predictions(),
      aiInsights.anomalies()
    ]).then(([preds, anom]: any) => {
      setPredictions(preds || []);
      setAnomalies(anom || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  if (loading) return <LoadingState rows={6} />;

  const avgScore = predictions.length
    ? Math.round(predictions.reduce((s, p) => s + p.risk_score, 0) / predictions.length)
    : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-50 text-blue-700 border border-blue-200 uppercase tracking-wide">
              Predictive Intelligence
            </span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900">AI Risk & Analytics Insights</h1>
          <p className="text-slate-500 text-sm mt-0.5">AI-Assisted Compliance Risk Analysis — Anomaly Detection & Predictive Governance</p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 border border-blue-200 rounded-md text-xs text-blue-700 font-semibold shadow-xs">
          <Brain size={14} /> AI Engine Online
        </div>
      </div>

      {/* Statutory Disclaimer */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-3.5 text-xs text-amber-900">
        ⚠ <strong>AI-Assisted Assessment Disclaimer:</strong> All risk scores and predictions are decision-support metrics generated by the CoalGuard compliance AI engine. They do not constitute definitive regulatory determinations under DGMS or Ministry of Coal guidelines.
      </div>

      {/* Summary KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Avg Risk Score', value: `${avgScore}/100`, text: avgScore > 60 ? 'text-red-700' : avgScore > 40 ? 'text-amber-700' : 'text-emerald-700' },
          { label: 'Total Predictions', value: predictions.length, text: 'text-slate-900' },
          { label: 'Active Anomalies', value: anomalies.length, text: anomalies.length > 0 ? 'text-orange-700' : 'text-emerald-700' },
          { label: 'Critical Risk', value: predictions.filter(p => p.risk_category === 'CRITICAL').length, text: 'text-red-700' },
        ].map(s => (
          <div key={s.label} className="bg-white border border-slate-200 rounded-lg p-4 shadow-card">
            <div className="text-xs text-slate-500 uppercase font-semibold tracking-wider">{s.label}</div>
            <div className={`text-2xl font-bold mt-1 ${s.text}`}>{s.value}</div>
          </div>
        ))}
      </div>

      {/* Predictions List */}
      <div className="space-y-4">
        {predictions.map(p => (
          <div key={p.id} className="bg-white border border-slate-200 rounded-lg shadow-card p-5">
            <div className="flex items-start justify-between mb-3 pb-3 border-b border-slate-100">
              <div className="flex items-center gap-3">
                <div
                  className="w-12 h-12 rounded-lg flex items-center justify-center text-xl font-black border"
                  style={{
                    backgroundColor: `${RISK_COLORS[p.risk_category]}10`,
                    borderColor: `${RISK_COLORS[p.risk_category]}30`,
                    color: RISK_COLORS[p.risk_category]
                  }}
                >
                  {Math.round(p.risk_score)}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <StatusBadge status={p.risk_category} />
                    <span className="text-xs text-slate-600 font-semibold bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                      {p.target_type}
                    </span>
                    {p.is_anomaly && (
                      <span className="flex items-center gap-1 text-[10px] text-orange-800 bg-orange-50 border border-orange-200 px-2 py-0.5 rounded font-bold">
                        <Zap size={10} /> ANOMALY DETECTED
                      </span>
                    )}
                  </div>
                  <div className="text-[11px] text-slate-500 mt-1">
                    Confidence: {(p.confidence * 100).toFixed(0)}% • Generated: {formatDateTime(p.prediction_timestamp)}
                  </div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-2xl font-black font-mono" style={{ color: RISK_COLORS[p.risk_category] }}>
                  {Math.round(p.risk_score)}<span className="text-sm font-normal text-slate-400">/100</span>
                </div>
              </div>
            </div>

            <p className="text-xs text-slate-700 leading-relaxed mb-3">{p.explanation}</p>

            {p.contributing_factors?.length > 0 && (
              <div className="mb-3 bg-slate-50 p-3 rounded-lg border border-slate-200">
                <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">Contributing Risk Factors</div>
                <ul className="space-y-1">
                  {p.contributing_factors.map((f: string, i: number) => (
                    <li key={i} className="flex items-start gap-2 text-xs">
                      <span className="text-orange-600 mt-0.5 font-bold">▪</span>
                      <span className="text-slate-700">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {p.is_anomaly && p.anomaly_details && Object.keys(p.anomaly_details).length > 0 && (
              <div className="bg-orange-50 border border-orange-200 rounded-lg p-3 mb-3 text-xs">
                <div className="flex items-center gap-1.5 text-orange-800 font-bold mb-1">
                  <AlertTriangle size={13} /> Operational Anomaly Detected
                </div>
                <div className="text-slate-600">
                  <strong>Metric:</strong> {p.anomaly_details.metric} •{' '}
                  <strong>Deviation:</strong> {p.anomaly_details.deviation_sigma || p.anomaly_details.deviation}
                </div>
              </div>
            )}

            {p.recommended_actions?.length > 0 && (
              <div>
                <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Recommended Actions</div>
                <div className="flex flex-wrap gap-2">
                  {p.recommended_actions.map((a: string, i: number) => (
                    <span key={i} className="text-xs bg-blue-50 border border-blue-200 text-blue-800 px-2.5 py-1 rounded font-medium">
                      {i + 1}. {a}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {predictions.length === 0 && <EmptyState message="No AI predictions available yet" />}
    </div>
  );
}
