import { useState, useEffect } from 'react';
import { Brain, AlertTriangle, TrendingUp, Zap } from 'lucide-react';
import {
  RadarChart, Radar, PolarGrid, PolarAngleAxis,
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell
} from 'recharts';
import { aiInsights } from '../services/api';
import { SectionCard, StatusBadge, LoadingState, EmptyState } from '../components/ui/UIComponents';
import { formatDateTime } from '../utils/helpers';

const RISK_COLORS: Record<string, string> = {
  LOW: '#10b981',
  MEDIUM: '#f59e0b',
  HIGH: '#f97316',
  CRITICAL: '#ef4444',
};

export default function AIInsightsPage() {
  const [predictions, setPredictions] = useState<any[]>([]);
  const [anomalies, setAnomalies] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      aiInsights.predictions(),
      aiInsights.anomalies()
    ]).then(([preds, anom]: any) => {
      setPredictions(preds || []);
      setAnomalies(anom || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  if (loading) return <LoadingState rows={6} />;

  const avgScore = predictions.length
    ? Math.round(predictions.reduce((s, p) => s + p.risk_score, 0) / predictions.length)
    : 0;

  const minePreds = predictions.filter(p => p.target_type === 'MINE');
  const contPreds = predictions.filter(p => p.target_type === 'CONTRACTOR');

  const chartData = predictions.map(p => ({
    name: p.target_type === 'MINE' ? 'Mine' : 'Contractor',
    risk: Math.round(p.risk_score),
    category: p.risk_category,
  }));

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">AI Risk & Analytics Insights</h1>
          <p className="text-coal-500 text-sm mt-0.5">AI-Assisted Compliance Risk Analysis — Anomaly Detection & Predictive Governance</p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 bg-blue-900/20 border border-blue-800/40 rounded-lg text-xs text-blue-400 font-medium">
          <Brain size={14} /> AI Engine Active
        </div>
      </div>

      {/* Disclaimer */}
      <div className="bg-amber-900/20 border border-amber-800/40 rounded-xl px-4 py-3 text-xs text-amber-300">
        ⚠ <strong>AI-Assisted Assessment Disclaimer:</strong> All risk scores and predictions are decision-support metrics generated by the CoalGuard compliance AI engine. They do not constitute definitive regulatory determinations under DGMS or Ministry of Coal guidelines.
      </div>

      {/* Summary KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { label: 'Avg Risk Score', value: `${avgScore}/100`, color: avgScore > 60 ? 'text-red-400' : avgScore > 40 ? 'text-yellow-400' : 'text-emerald-400' },
          { label: 'Total Predictions', value: predictions.length, color: 'text-white' },
          { label: 'Active Anomalies', value: anomalies.length, color: anomalies.length > 0 ? 'text-orange-400' : 'text-emerald-400' },
          { label: 'Critical Risk', value: predictions.filter(p => p.risk_category === 'CRITICAL').length, color: 'text-red-400' },
        ].map(s => (
          <div key={s.label} className="kpi-card">
            <div className="text-[10px] text-coal-500 uppercase font-semibold">{s.label}</div>
            <div className={`text-2xl font-bold mt-1 ${s.color}`}>{s.value}</div>
          </div>
        ))}
      </div>

      {/* Predictions List */}
      <div className="space-y-4">
        {predictions.map(p => (
          <div key={p.id} className="section-card">
            <div className="p-5">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-xl font-black`}
                    style={{ background: `${RISK_COLORS[p.risk_category]}20`, color: RISK_COLORS[p.risk_category] }}>
                    {Math.round(p.risk_score)}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <StatusBadge status={p.risk_category} />
                      <span className="text-xs text-coal-500 bg-coal-800 px-2 py-0.5 rounded-lg">
                        {p.target_type}
                      </span>
                      {p.is_anomaly && (
                        <span className="flex items-center gap-1 text-[10px] text-orange-400 bg-orange-900/30 border border-orange-800/40 px-2 py-0.5 rounded-lg font-semibold">
                          <Zap size={9} /> ANOMALY DETECTED
                        </span>
                      )}
                    </div>
                    <div className="text-[10px] text-coal-500 mt-1">
                      Confidence: {(p.confidence * 100).toFixed(0)}% • Generated: {formatDateTime(p.prediction_timestamp)}
                    </div>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-black" style={{ color: RISK_COLORS[p.risk_category] }}>
                    {Math.round(p.risk_score)}<span className="text-base">/100</span>
                  </div>
                </div>
              </div>

              <p className="text-sm text-coal-300 mb-3">{p.explanation}</p>

              {p.contributing_factors?.length > 0 && (
                <div className="mb-3">
                  <div className="text-[10px] font-bold text-coal-500 uppercase mb-2">Contributing Risk Factors</div>
                  <ul className="space-y-1.5">
                    {p.contributing_factors.map((f: string, i: number) => (
                      <li key={i} className="flex items-start gap-2 text-xs">
                        <span className="text-orange-400 mt-0.5 flex-shrink-0">▶</span>
                        <span className="text-coal-300">{f}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {p.is_anomaly && p.anomaly_details && Object.keys(p.anomaly_details).length > 0 && (
                <div className="bg-orange-900/20 border border-orange-800/40 rounded-xl px-4 py-3 mb-3">
                  <div className="flex items-center gap-2 text-orange-400 font-semibold text-xs mb-1">
                    <AlertTriangle size={12} /> Operational Anomaly Detected
                  </div>
                  <div className="text-xs text-coal-400">
                    <strong>Metric:</strong> {p.anomaly_details.metric} •{' '}
                    <strong>Deviation:</strong> {p.anomaly_details.deviation_sigma || p.anomaly_details.deviation}
                  </div>
                </div>
              )}

              {p.recommended_actions?.length > 0 && (
                <div>
                  <div className="text-[10px] font-bold text-coal-500 uppercase mb-2">Recommended Actions</div>
                  <div className="flex flex-wrap gap-2">
                    {p.recommended_actions.map((a: string, i: number) => (
                      <span key={i} className="text-[10px] bg-blue-900/30 border border-blue-800/40 text-blue-300 px-2 py-1 rounded-lg">
                        {i + 1}. {a}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {predictions.length === 0 && <EmptyState message="No AI predictions available yet" />}
    </div>
  );
}
